/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  alias(libs.plugins.kotlin.jvm)

  // Apply the application plugin to add support for building a CLI application in Java.
  application
}

repositories {
  mavenLocal()
  google()
  mavenCentral()
}

dependencies {
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")

  // This dependency is used by the application.
  implementation(libs.guava)
  implementation("com.google.ai.edge.litertlm:litertlm-jvm:0.0.0-alpha06")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

application {
  // Define the main class for the application.
  mainClass = "org.example.AppKt"
}

tasks.named<JavaExec>("run") {
  standardInput = System.`in`
}

tasks.run {
  systemProperties["com.google.ai.edge.litertlm.NativeLibraryLoader.DEBUG"] = "true"
}
